version: "3.8"

services:
  # Local Lambda function development environment
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro # For AWS CLI credentials (read-only)
    env_file:
      - .env
    command: /bin/bash
    tty: true
    stdin_open: true
    depends_on:
      - localstack

  # LocalStack for simulating AWS services locally
  localstack:
    image: localstack/localstack:latest
    ports:
      - "${LOCALSTACK_PORT}:4566" # LocalStack edge port
    environment:
      - SERVICES=${LOCALSTACK_SERVICES}
      - DEBUG=${LOCALSTACK_DEBUG}
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d # Initialization scripts
      - localstack-data:/tmp/localstack

  # PostgreSQL for storing historical snowfall data (optional)
  postgres:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Adminer for database management (optional)
  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres

volumes:
  localstack-data:
  postgres-data:
