version: "3.8"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env.test
    environment:
      - USE_MOCK_DATA=${USE_MOCK_DATA}
      - DISABLE_NOTIFICATIONS=${DISABLE_NOTIFICATIONS}
      - PYTHONPATH=/app
    command: >
      bash -c "cd /app &&
              python -m pytest tests/ -v --cov=src --cov-report=term --cov-report=html"

  # LocalStack for AWS service simulation in tests
  localstack:
    image: localstack/localstack:latest
    ports:
      - "${LOCALSTACK_PORT}:4566"
    environment:
      - SERVICES=${LOCALSTACK_SERVICES}
      - DEBUG=${LOCALSTACK_DEBUG}
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

volumes:
  localstack-data:
